language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - phpunit

after_script:
    - php ./vendor/bin/coveralls -v

notifications:
  email:
    - ja.izquierdo.galan@gmail.com
