language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly
s
before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - phpunit

notifications:
  email:
    - ja.izquierdo.galan@gmail.com
